version: '3.8'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d


  airflow:
    image: apache/airflow:2.7.0
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres:5432/postgres
      AIRFLOW__WEBSERVER__RBAC: 'True'
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./requirements.txt:/requirements.txt
      - ./utils:/usr/local/airflow/utils
    env_file:
      - /.env

    command: >
      bash -c "export PYTHONPATH=/usr/local/airflow:/usr/local/airflow/utils &&
                pip install --no-cache-dir -r /requirements.txt &&
                airflow db init &&
                airflow db migrate &&
                airflow connections create-default-connections &&
                airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin &&
                airflow scheduler &
                sleep 10 &&
                airflow webserver"
  

  weather_app:
    build:
      context: ./weather_app
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - airflow
    ports:
      - "8501:8501"
    env_file:
      - /.env
    volumes:
      - ./utils:/app/utils
      - ./logs:/app/logs

volumes:
  pgdata:

